import { Suspense } from "react"
import Navbar from "../components/navbar/Navbar"
import Loading from "./loading"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="text-peach font-serif bg-indigo-950">
      <body>
        <Navbar/>
        <Suspense fallback={<Loading/>}>
          {children}
        </Suspense>
      </body>
    </html>
  )
}
